// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    partial class SupermarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà lon"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai, bơ"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì, phở, cháo gói, hủ tiếu ăn liền"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu ăn, nước tương"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Gạo, Bột & Khô",
                            Description = "Gạo thơm, bột mỹ, miến, bún khô"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Đồ đóng hộp & Chế biến sẵn",
                            Description = "Cá hộp, thịt hộp, xúc xích, pate"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Hóa mỹ phẩm & Vệ sinh cá nhân",
                            Description = "Dầu gội, sữa tắm, kem đánh răng, xà phòng"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Chăm sóc nhà cửa",
                            Description = "Nước lau sàn, nước rửa chén, bột giặt"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Khăn giấy & Tã bỉm",
                            Description = "Giấy vệ sinh, khăn giấy khô/ướt, tã em bé"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Cá viên, bò viên, chả giò, há cảo"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Kem & Đồ lạnh",
                            Description = "Kem que, kem hộp, đá viên đóng túi"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Bia & Đồ uống có cồn",
                            Description = "Bia lon, rượu nhẹ, cồn thực phẩm"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Cà phê & Cacao",
                            Description = "Cà phê hòa tan, cà phê rang xay, bột cacao"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Trái cây tươi Phố Thị",
                            Description = "Táo, chuối, cam, dưa hấu theo mùa"
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Rau củ & Nấm tươi",
                            Description = "Rau cải, cà chua, khoai tây, nấm rơm"
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Thực phẩm tươi sống",
                            Description = "Thịt heo, thịt gà, trứng gia cầm"
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Hạt & Đồ khô ăn kiêng",
                            Description = "Hạt điều, hạnh nhân, yến mạch, granola"
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Bánh tươi Phố Thị",
                            Description = "Bánh mì sandwich, bánh giò, bánh bao"
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Đồ dùng gia đình nhỏ",
                            Description = "Màng bọc thực phẩm, túi bóng, đũa muỗng"
                        },
                        new
                        {
                            CategoryId = 21,
                            CategoryName = "Văn phòng phẩm tạp hóa",
                            Description = "Bút, tập học sinh, băng keo, kéo"
                        },
                        new
                        {
                            CategoryId = 22,
                            CategoryName = "Chăm sóc thú cưng",
                            Description = "Thức ăn cho chó mèo, cát vệ sinh"
                        },
                        new
                        {
                            CategoryId = 23,
                            CategoryName = "Sản phẩm Mẹ & Bé",
                            Description = "Sữa bột, bình sữa, rơ lưỡi, ty giả"
                        },
                        new
                        {
                            CategoryId = 24,
                            CategoryName = "Thuốc không kê đơn & Y tế",
                            Description = "Khẩu y tế, bông gòn, dầu gió, C sủi"
                        },
                        new
                        {
                            CategoryId = 25,
                            CategoryName = "Đồ kim khí & Điện gia dụng",
                            Description = "Pin AA/AAA, bóng đèn, ổ cắm, băng keo điện"
                        },
                        new
                        {
                            CategoryId = 26,
                            CategoryName = "Trà thảo mộc & Đông y",
                            Description = "Trà atiso, trà hoa cúc, mủ trôm, hạt chia"
                        },
                        new
                        {
                            CategoryId = 27,
                            CategoryName = "Nước mát Phố Thị",
                            Description = "Nước nha đam, sâm mát, rau má đóng chai"
                        },
                        new
                        {
                            CategoryId = 28,
                            CategoryName = "Đồ ăn vặt truyền thống",
                            Description = "Bánh tráng trộn, cơm cháy, mứt tép"
                        },
                        new
                        {
                            CategoryId = 29,
                            CategoryName = "Thời trang & Phụ kiện nhỏ",
                            Description = "Khẩu trang vải, tất chân, áo mưa tiện lợi"
                        },
                        new
                        {
                            CategoryId = 30,
                            CategoryName = "Đồ lưu niệm & Quà tặng Phố Thị",
                            Description = "Túi vải Phố Thị, thiệp mừng, gấu bông nhỏ"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chuẩn");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CustomerId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "12 Nguyễn Trãi, Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "45 Lê Lợi, Q.1, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "88 CMT8, Q.3, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "102 Võ Văn Tần, Q.3, TP.HCM",
                            CustomerName = "Phạm Hoàng Dũng",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0934567891",
                            RewardPoints = 520
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "15 Lý Tự Trọng, Q.1, TP.HCM",
                            CustomerName = "Hoàng Thị Mai",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0978123456",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "23 Trần Hưng Đạo, Q.5, TP.HCM",
                            CustomerName = "Vũ Đình Trọng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0965432187",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "67 Nguyễn Thị Minh Khai, Q.3, TP.HCM",
                            CustomerName = "Đặng Thu Thảo",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0923456789",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "120 Điện Biên Phủ, Bình Thạnh, TP.HCM",
                            CustomerName = "Bùi Anh Tuấn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0945678912",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "89 Hai Bà Trưng, Q.1, TP.HCM",
                            CustomerName = "Đỗ Kim Ngân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0912345678",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "34 Hoàng Văn Thụ, Phú Nhuận, TP.HCM",
                            CustomerName = "Hồ Văn Khoa",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0987654321",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "56 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM",
                            CustomerName = "Ngoạn Thị Bích",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909988776",
                            RewardPoints = 5
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "11 Sư Vạn Hạnh, Q.10, TP.HCM",
                            CustomerName = "Dương Quốc Bảo",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0933221100",
                            RewardPoints = 610
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "223 Ba Tháng Hai, Q.10, TP.HCM",
                            CustomerName = "Lý Mỹ Linh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0977665544",
                            RewardPoints = 70
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "44 Phan Đăng Lưu, Phú Nhuận, TP.HCM",
                            CustomerName = "Huỳnh Minh Trí",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0944556677",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "78 Lê Văn Sỹ, Q.3, TP.HCM",
                            CustomerName = "Phan Thị Mỹ",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0911223344",
                            RewardPoints = 300
                        },
                        new
                        {
                            CustomerId = 16,
                            Address = "90 Nguyễn Trãi, Q.5, TP.HCM",
                            CustomerName = "Ngô Thành Nam",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0988990011",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 17,
                            Address = "101 Nguyễn Đình Chiểu, Q.3, TP.HCM",
                            CustomerName = "Trịnh Khánh Vy",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0931122334",
                            RewardPoints = 60
                        },
                        new
                        {
                            CustomerId = 18,
                            Address = "12 Đinh Tiên Hoàng, Q.1, TP.HCM",
                            CustomerName = "Đinh Văn Hùng",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0961122334",
                            RewardPoints = 30
                        },
                        new
                        {
                            CustomerId = 19,
                            Address = "55 Pasteur, Q.1, TP.HCM",
                            CustomerName = "Lương Hải Yến",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0921122334",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 20,
                            Address = "88 Nam Kỳ Khởi Nghĩa, Q.1, TP.HCM",
                            CustomerName = "Mai Văn Hải",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0951122334",
                            RewardPoints = 12
                        },
                        new
                        {
                            CustomerId = 21,
                            Address = "202 Bùi Viện, Q.1, TP.HCM",
                            CustomerName = "Cao Thị Hương",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0971122334",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 22,
                            Address = "333 Nguyễn Oanh, Gò Vấp, TP.HCM",
                            CustomerName = "Tạ Quang Khải",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0941122334",
                            RewardPoints = 8
                        },
                        new
                        {
                            CustomerId = 23,
                            Address = "150 Quang Trung, Gò Vấp, TP.HCM",
                            CustomerName = "Trương Tấn Phát",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0919988776",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 24,
                            Address = "66 Phạm Văn Đồng, Thủ Đức, TP.HCM",
                            CustomerName = "Thái Thị Ánh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989988776",
                            RewardPoints = 190
                        },
                        new
                        {
                            CustomerId = 25,
                            Address = "12 Võ Văn Ngân, Thủ Đức, TP.HCM",
                            CustomerName = "Lâm Văn Thanh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0939988776",
                            RewardPoints = 2
                        },
                        new
                        {
                            CustomerId = 26,
                            Address = "88 Kha Vạn Cân, Thủ Đức, TP.HCM",
                            CustomerName = "Đào Thúy Hằng",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0969988776",
                            RewardPoints = 55
                        },
                        new
                        {
                            CustomerId = 27,
                            Address = "45 Lê Văn Việt, Q.9, TP.HCM",
                            CustomerName = "Vương Đình Tấn",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0929988776",
                            RewardPoints = 18
                        },
                        new
                        {
                            CustomerId = 28,
                            Address = "77 Đỗ Xuân Hợp, Q.9, TP.HCM",
                            CustomerName = "Nguyễn Ngọc Ánh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0959988776",
                            RewardPoints = 230
                        },
                        new
                        {
                            CustomerId = 29,
                            Address = "12 Nguyễn Duy Trinh, Q.2, TP.HCM",
                            CustomerName = "Trần Bảo Lâm",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0979988776",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 30,
                            Address = "01 Thảo Điền, Q.2, TP.HCM",
                            CustomerName = "Lê Thị Hồng",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0949988776",
                            RewardPoints = 950
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "893456789001",
                            CategoryId = 1,
                            Price = 12000m,
                            ProductName = "Bánh Lay's Vị Tự Nhiên 63g",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "893456789002",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Kẹo Dẻo Haribo Goldbears 80g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "893456789003",
                            CategoryId = 2,
                            Price = 10000m,
                            ProductName = "Nước Ngọt Coca-Cola Lon 320ml",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "893456789004",
                            CategoryId = 2,
                            Price = 8000m,
                            ProductName = "Trà Green Tea C2 Vị Chanh 360ml",
                            StockQuantity = 250
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "893456789005",
                            CategoryId = 3,
                            Price = 38000m,
                            ProductName = "Sữa Tươi Vinamilk Ít Đường 1L",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "893456789006",
                            CategoryId = 3,
                            Price = 28000m,
                            ProductName = "Sữa Chua TH True Milk Lốc 4 Hộp",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "893456789007",
                            CategoryId = 4,
                            Price = 4500m,
                            ProductName = "Mì Hảo Hảo Vị Tôm Chua Cay 75g",
                            StockQuantity = 500
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "893456789008",
                            CategoryId = 4,
                            Price = 8500m,
                            ProductName = "Phở Bò Đệ Nhất Gói 120g",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "893456789009",
                            CategoryId = 5,
                            Price = 42000m,
                            ProductName = "Nước Mắm Nam Ngư Đệ Nhất 900ml",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "893456789010",
                            CategoryId = 5,
                            Price = 52000m,
                            ProductName = "Dầu Ăn Tường An Cooking Oil 1L",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "893456789011",
                            CategoryId = 6,
                            Price = 180000m,
                            ProductName = "Gạo ST25 Phố Thị Túi 5kg",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "893456789012",
                            CategoryId = 7,
                            Price = 19000m,
                            ProductName = "Cá Sốt Cà Ba Cô Gái Hộp 155g",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "893456789013",
                            CategoryId = 8,
                            Price = 135000m,
                            ProductName = "Dầu Gội Sunsilk Mềm Mượt 650g",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "893456789014",
                            CategoryId = 9,
                            Price = 32000m,
                            ProductName = "Nước Rửa Chén Sunlight Chanh 750ml",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "893456789015",
                            CategoryId = 10,
                            Price = 75000m,
                            ProductName = "Giấy Vệ Sinh Pulppy 10 Cuộn",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 16,
                            Barcode = "893456789016",
                            CategoryId = 11,
                            Price = 65000m,
                            ProductName = "Chả Giò Cầu Tre Nhân Thịt 500g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 17,
                            Barcode = "893456789017",
                            CategoryId = 12,
                            Price = 12000m,
                            ProductName = "Kem Merino Đậu Đỏ Que 60g",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 18,
                            Barcode = "893456789018",
                            CategoryId = 13,
                            Price = 18500m,
                            ProductName = "Bia Tiger Lon 330ml",
                            StockQuantity = 400
                        },
                        new
                        {
                            ProductId = 19,
                            Barcode = "893456789019",
                            CategoryId = 14,
                            Price = 58000m,
                            ProductName = "Cà Phê G7 3in1 Hộp 18 Gói",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 20,
                            Barcode = "893456789020",
                            CategoryId = 15,
                            Price = 25000m,
                            ProductName = "Cam Sành Miền Tây (1kg)",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 21,
                            Barcode = "893456789021",
                            CategoryId = 16,
                            Price = 15000m,
                            ProductName = "Cà Chua Đà Lạt Fresh (500g)",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 22,
                            Barcode = "893456789022",
                            CategoryId = 17,
                            Price = 31000m,
                            ProductName = "Trứng Gà Tươi Vĩnh Thành Đạt (Hộp 10 quả)",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 23,
                            Barcode = "893456789023",
                            CategoryId = 18,
                            Price = 68000m,
                            ProductName = "Hạt Điều Rang Salted Phố Thị 200g",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 24,
                            Barcode = "893456789024",
                            CategoryId = 19,
                            Price = 22000m,
                            ProductName = "Bánh Mì Sandwich Kinh Đô 275g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 25,
                            Barcode = "893456789025",
                            CategoryId = 20,
                            Price = 35000m,
                            ProductName = "Màng Bọc Thực Phẩm Lasms 30cm",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 26,
                            Barcode = "893456789026",
                            CategoryId = 21,
                            Price = 6000m,
                            ProductName = "Bút Cầu Gel Thiên Long 0.5mm",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 27,
                            Barcode = "893456789027",
                            CategoryId = 22,
                            Price = 16000m,
                            ProductName = "Pate Cho Mèo Whiskas Vị Cá Biển 85g",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 28,
                            Barcode = "893456789028",
                            CategoryId = 24,
                            Price = 35000m,
                            ProductName = "Khẩu Trang Y Tế 4 Lớp Phố Thị (Hộp 50 cái)",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 29,
                            Barcode = "893456789029",
                            CategoryId = 25,
                            Price = 20000m,
                            ProductName = "Pin AA Panasonic Hyper Vỉ 4 Viên",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 30,
                            Barcode = "893456789030",
                            CategoryId = 28,
                            Price = 28000m,
                            ProductName = "Cơm Cháy Chà Bông Phố Thị 150g",
                            StockQuantity = 90
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị viên toàn hệ thống, toàn quyền thao tác",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhân viên thu ngân, chuyên trách bán hàng tại quầy POS",
                            RoleName = "Cashier"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhân viên quản lý kho, nhập hàng và kiểm kê",
                            RoleName = "Warehouse"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Quản lý cửa hàng Phố Thị, giám sát vận hành chung",
                            RoleName = "StoreManager"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Trợ lý quản lý cửa hàng Phố Thị",
                            RoleName = "AssistantManager"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Quản lý tồn kho và kế hoạch dự trữ",
                            RoleName = "InventoryManager"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Nhân viên thu mua hàng hóa tạp hóa",
                            RoleName = "PurchasingStaff"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Trưởng phòng thu mua, duyệt đơn nhập hàng",
                            RoleName = "PurchasingManager"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Nhân viên kế toán, thu chi và hóa đơn",
                            RoleName = "Accountant"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Kế toán trưởng Phố Thị",
                            RoleName = "ChiefAccountant"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Nhân viên bán hàng & tư vấn trực tiếp",
                            RoleName = "SalesStaff"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Giám sát sảnh và gian hàng Phố Thị",
                            RoleName = "FloorSupervisor"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Nhân viên chăm sóc & giải quyết khiếu nại",
                            RoleName = "CustomerService"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Quản lý chương trình khách hàng thân thiết",
                            RoleName = "CRMManager"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Nhân viên marketing & chương trình khuyến mãi",
                            RoleName = "MarketingStaff"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Trưởng phòng tiếp thị & truyền thông Phố Thị",
                            RoleName = "MarketingManager"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Nhân viên hỗ trợ kỹ thuật POS và hệ thống",
                            RoleName = "ITSupport"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Quản trị viên hạ tầng mạng & cơ sở dữ liệu",
                            RoleName = "SysAdmin"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Nhân viên bảo vệ & giữ xe cửa hàng",
                            RoleName = "SecurityGuard"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Nhân viên giao hàng Phố Thị Express",
                            RoleName = "DeliveryStaff"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Quản lý vận chuyển & giao nhận",
                            RoleName = "LogisticsManager"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Nhân viên nhân sự & chấm công",
                            RoleName = "HRStaff"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Trưởng phòng nhân sự & tuyển dụng",
                            RoleName = "HRManager"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Nhân viên trưng bày & sắp xếp kệ hàng",
                            RoleName = "Merchandiser"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Kiểm định chất lượng & hạn sử dụng (HSD)",
                            RoleName = "QualityControl"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Nhân viên kiểm toán nội bộ & thất thoát",
                            RoleName = "AuditStaff"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Trưởng ca làm việc Phố Thị",
                            RoleName = "ShiftLeader"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Chuyên viên phân tích doanh thu & xu hướng",
                            RoleName = "DataAnalyst"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Nhân viên quản lý đơn hàng online",
                            RoleName = "EcomStaff"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Giám đốc điều hành chuỗi Tạp hóa Phố Thị",
                            RoleName = "GeneralManager"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
